/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lge_ccdevs_tracker_CameraActivity */

#ifndef _Included_com_lge_ccdevs_tracker_CameraActivity
#define _Included_com_lge_ccdevs_tracker_CameraActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lge_ccdevs_tracker_CameraActivity
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lge_ccdevs_tracker_CameraActivity_native_1init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
