/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lge_ccdevs_tracker_CameraPreview */

#ifndef _Included_com_lge_ccdevs_tracker_CameraPreview
#define _Included_com_lge_ccdevs_tracker_CameraPreview
#ifdef __cplusplus
extern "C" {
#endif

#undef com_lge_ccdevs_tracker_CameraPreview_FRAME_COUNT
#define com_lge_ccdevs_tracker_CameraPreview_FRAME_COUNT 10L
/*
 * Class:     com_lge_ccdevs_tracker_CameraPreview
 * Method:    native_cv_facex
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_lge_ccdevs_tracker_CameraPreview_native_1cv_1facex
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_lge_ccdevs_tracker_CameraPreview
 * Method:    native_cv_init
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/RectF;)V
 */
JNIEXPORT void JNICALL Java_com_lge_ccdevs_tracker_CameraPreview_native_1cv_1init__Landroid_graphics_Bitmap_2Landroid_graphics_RectF_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_lge_ccdevs_tracker_CameraPreview
 * Method:    native_cv_init
 * Signature: (Landroid/graphics/Bitmap;[F)V
 */
JNIEXPORT void JNICALL Java_com_lge_ccdevs_tracker_CameraPreview_native_1cv_1init__Landroid_graphics_Bitmap_2_3F
  (JNIEnv *, jobject, jobject, jfloatArray);

/*
 * Class:     com_lge_ccdevs_tracker_CameraPreview
 * Method:    native_cv_track
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/RectF;
 */
JNIEXPORT jobject JNICALL Java_com_lge_ccdevs_tracker_CameraPreview_native_1cv_1track
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_lge_ccdevs_tracker_CameraPreview
 * Method:    native_cv_match
 * Signature: (Landroid/graphics/Bitmap;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_lge_ccdevs_tracker_CameraPreview_native_1cv_1match
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
